package Vista;

import Controlador.ControladorSolicitudMantenimiento;
import Controlador.ControladorVuelo;
import Exepciones.mismoOrigenException;
import Exepciones.noExisteVueloException;
import Exepciones.solicitudExistenteexeption;
import Exepciones.vueloDuplicadoException;
import Modelo.Aerolinea;
import Modelo.Avion;
import Modelo.CapitanVuelo;
import Modelo.SolicitudMantenimiento;
import Modelo.Vuelo;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Juan
 */
public class VentanaEmpleado extends javax.swing.JFrame {

    ControladorVuelo controladorVuelo;
    ControladorSolicitudMantenimiento controladorSolicitudMantenimiento;
    Aerolinea aeroline;

    public VentanaEmpleado() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public VentanaEmpleado(Aerolinea aeroline) {
        initComponents();
        setLocationRelativeTo(this);
        this.controladorVuelo = new ControladorVuelo();
        this.controladorSolicitudMantenimiento = new ControladorSolicitudMantenimiento();
        this.aeroline = aeroline;
        jdcFechaVuelo.setMinSelectableDate(new Date());
        jdcFechaS.setMinSelectableDate(new Date());
        incializarComboBoxOrigen();
        incializarComboBoxDestino();
        incializarComboBoxHoraSalida();
        incializarComboBoxMinutoSalida();
        incializarComboBoxHoraTrayectoria();
        incializarComboBoxMinutoTrayectoria();
        llenarCbCapitan(aeroline);
        llenarCbAvion(aeroline);
        actualizarAviones();
        actualizarTabla();
        actualizarSolicitud();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdcFechaVuelo = new com.toedter.calendar.JDateChooser();
        txtCodigoVuelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRegistrar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cbOrigen = new javax.swing.JComboBox<>();
        cbDestino = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbAvion = new javax.swing.JComboBox<>();
        cbCapitan = new javax.swing.JComboBox<>();
        cbHoraSalida = new javax.swing.JComboBox<>();
        cbMinutoSalida = new javax.swing.JComboBox<>();
        cbHoraTrayectoria = new javax.swing.JComboBox<>();
        cbMinutoTrayectoria = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSolicitud = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAvion = new javax.swing.JTable();
        btnSolicitud = new javax.swing.JButton();
        btnBuscarS = new javax.swing.JButton();
        btnModificarS = new javax.swing.JButton();
        btnEliminarS = new javax.swing.JButton();
        txtCodigoS = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbAvionS = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jdcFechaS = new com.toedter.calendar.JDateChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        btnChat = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Origen");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Destino");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo de Avion");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Capitan");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha");

        jdcFechaVuelo.setBackground(new java.awt.Color(255, 255, 255));
        jdcFechaVuelo.setForeground(new java.awt.Color(0, 0, 0));

        txtCodigoVuelo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoVuelo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoVueloActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Hora De Salida");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tiempo De");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Trayectoria");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Codigo Vuelo");

        txtRegistrar.setBackground(new java.awt.Color(255, 214, 94));
        txtRegistrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        txtRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        txtRegistrar.setText("Registrar");
        txtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrarActionPerformed(evt);
            }
        });

        txtBuscar.setBackground(new java.awt.Color(255, 214, 94));
        txtBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setText("Buscar");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 214, 94));
        btnModificar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 214, 94));
        btnEliminar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        cbOrigen.setBackground(new java.awt.Color(255, 255, 255));
        cbOrigen.setForeground(new java.awt.Color(0, 0, 0));

        cbDestino.setBackground(new java.awt.Color(255, 255, 255));
        cbDestino.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Horas");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Minutos");

        cbAvion.setBackground(new java.awt.Color(255, 255, 255));
        cbAvion.setForeground(new java.awt.Color(0, 0, 0));
        cbAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAvionActionPerformed(evt);
            }
        });

        cbCapitan.setBackground(new java.awt.Color(255, 255, 255));
        cbCapitan.setForeground(new java.awt.Color(0, 0, 0));
        cbCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCapitanActionPerformed(evt);
            }
        });

        cbHoraSalida.setBackground(new java.awt.Color(255, 255, 255));
        cbHoraSalida.setForeground(new java.awt.Color(0, 0, 0));

        cbMinutoSalida.setBackground(new java.awt.Color(255, 255, 255));
        cbMinutoSalida.setForeground(new java.awt.Color(0, 0, 0));

        cbHoraTrayectoria.setBackground(new java.awt.Color(255, 255, 255));
        cbHoraTrayectoria.setForeground(new java.awt.Color(0, 0, 0));

        cbMinutoTrayectoria.setBackground(new java.awt.Color(255, 255, 255));
        cbMinutoTrayectoria.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(txtRegistrar)
                .addGap(42, 42, 42)
                .addComponent(btnModificar)
                .addGap(34, 34, 34)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoVuelo)
                                .addComponent(jdcFechaVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addComponent(cbOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbAvion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCapitan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(39, 39, 39)
                                .addComponent(cbHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbHoraTrayectoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbMinutoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMinutoTrayectoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(243, 243, 243))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jdcFechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMinutoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbHoraTrayectoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMinutoTrayectoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(txtBuscar)
                    .addComponent(btnEliminar))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestion de Vuelos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listado de Vuelos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblSolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSolicitud);

        tblAvion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblAvion);

        btnSolicitud.setBackground(new java.awt.Color(255, 214, 94));
        btnSolicitud.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitud.setText("Solicitar");
        btnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudActionPerformed(evt);
            }
        });

        btnBuscarS.setBackground(new java.awt.Color(255, 214, 94));
        btnBuscarS.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnBuscarS.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarS.setText("Buscar");
        btnBuscarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSActionPerformed(evt);
            }
        });

        btnModificarS.setBackground(new java.awt.Color(255, 214, 94));
        btnModificarS.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnModificarS.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarS.setText("Modificar");
        btnModificarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSActionPerformed(evt);
            }
        });

        btnEliminarS.setBackground(new java.awt.Color(255, 214, 94));
        btnEliminarS.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnEliminarS.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarS.setText("Eliminar");
        btnEliminarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSActionPerformed(evt);
            }
        });

        txtCodigoS.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoS.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoSActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("ID");

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Codigo de Avion");

        cbAvionS.setBackground(new java.awt.Color(255, 255, 255));
        cbAvionS.setForeground(new java.awt.Color(0, 0, 0));
        cbAvionS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAvionSActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Fecha");

        jdcFechaS.setBackground(new java.awt.Color(255, 255, 255));
        jdcFechaS.setForeground(new java.awt.Color(0, 0, 0));

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane4.setViewportView(txtObservacion);

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Observación");

        btnChat.setBackground(new java.awt.Color(255, 214, 94));
        btnChat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnChat.setForeground(new java.awt.Color(0, 0, 0));
        btnChat.setText("Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnModificarS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jdcFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoS, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(cbAvionS, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(cbAvionS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarS)
                    .addComponent(btnSolicitud))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarS)
                            .addComponent(btnModificarS))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btnChat)
                        .addGap(31, 31, 31))))
        );

        jTabbedPane1.addTab("Solicitudes de Mantenimiento", jPanel3);

        btnLogin.setBackground(new java.awt.Color(255, 214, 94));
        btnLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        VentanaLogin ventana = new VentanaLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void actualizarSolicitud() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"ID", "FECHA", "AVION", "OBSERVACIÓN"},
                aeroline.getListaSolicitud().size());
        tblSolicitud.setModel(modelo);
        TableModel modeloDatos = tblSolicitud.getModel();
        for (int i = 0; i < aeroline.getListaSolicitud().size(); i++) {
            SolicitudMantenimiento aux = aeroline.getListaSolicitud().get(i);
            modeloDatos.setValueAt(aux.getId(), i, 0);
            modeloDatos.setValueAt(aux.getFecha().toString(), i, 1);
            modeloDatos.setValueAt(aux.getAvion(), i, 2);
            modeloDatos.setValueAt(aux.getObservacion(), i, 3);
        }
    }


    private void txtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrarActionPerformed
        try {
            String origen = cbOrigen.getSelectedItem().toString();
            String destino = cbDestino.getSelectedItem().toString();
            int horasalida = Integer.parseInt(cbHoraSalida.getSelectedItem().toString());
            int minutoSalida = Integer.parseInt(cbMinutoSalida.getSelectedItem().toString());
            int horatiempoTrayectoria = Integer.parseInt(cbHoraTrayectoria.getSelectedItem().toString());
            int minutoTrayectoria = Integer.parseInt(cbMinutoTrayectoria.getSelectedItem().toString());
            String codigovuelo = txtCodigoVuelo.getText();
            Avion codigoAvion = (Avion) cbAvion.getSelectedItem();
            CapitanVuelo capitan = (CapitanVuelo) cbCapitan.getSelectedItem();
            Date fechaAux = jdcFechaVuelo.getDate();
            LocalDate fecha = fechaAux.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            LocalTime fechaHora = LocalTime.of(horasalida, minutoSalida);
            LocalDateTime fechaSalida = LocalDateTime.of(fecha, fechaHora);
            LocalDateTime fechaLlegada = fechaSalida.plusHours(horatiempoTrayectoria);
            fechaLlegada.plusMinutes(minutoTrayectoria);
            Vuelo vuel = new Vuelo(origen, destino, fechaSalida, fechaLlegada, codigovuelo, codigoAvion, capitan);
            Vuelo vuelo2 = controladorVuelo.validacionOrigen(aeroline, vuel);
            if (vuelo2 != null) {
                int E = JOptionPane.showConfirmDialog(null, "El vuelo ya se encuentra en otro Ciudad quiere cambiar el punto de origen");
                if (E == 0) {
                    Vuelo vu1 = new Vuelo(vuelo2.getDestino(), destino, fechaSalida, fechaLlegada, codigovuelo, codigoAvion, capitan);
                    this.aeroline = controladorVuelo.guardarVuelo(aeroline, vu1);
                    actualizarTabla();
                    limpiarVuelo();
                    JOptionPane.showMessageDialog(null, "Se guardo El Vuelo");
                }
            } else {
                this.aeroline=controladorVuelo.guardarVuelo(aeroline, vuel);
                JOptionPane.showMessageDialog(null, "Se guardo El Vuelo");
                actualizarTabla();
                limpiarVuelo();
            }
        } catch (mismoOrigenException | vueloDuplicadoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_txtRegistrarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String codigovuelo = txtCodigoVuelo.getText();
        Vuelo respuesta = controladorVuelo.buscarVuelo(aeroline, codigovuelo);
        if (respuesta != null) {
            cbOrigen.setSelectedItem(respuesta.getOrigen());
            cbDestino.setSelectedItem(respuesta.getDestino());
            jdcFechaVuelo.setDate(java.sql.Date.valueOf(respuesta.getFechaLlegada().toLocalDate()));
            cbHoraSalida.setSelectedItem(String.valueOf(respuesta.getFechaSalida().getHour()));
            cbMinutoSalida.setSelectedItem(String.valueOf(respuesta.getFechaSalida().getMinute()));
            cbHoraTrayectoria.setSelectedItem(String.valueOf(respuesta.getFechaLlegada().getHour()));
            cbMinutoTrayectoria.setSelectedItem(String.valueOf(respuesta.getFechaLlegada().getMinute()));
            cbAvion.setSelectedItem(respuesta.getAvion());
            cbCapitan.setSelectedItem(respuesta.getCapitan());
        } else {
            JOptionPane.showMessageDialog(null, " No  Existe El Vuelo");
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        try {
            String origen = cbOrigen.getSelectedItem().toString();
            String destino = cbDestino.getSelectedItem().toString();
            int horasalida = Integer.parseInt(cbHoraSalida.getSelectedItem().toString());
            int minutoSalida = Integer.parseInt(cbMinutoSalida.getSelectedItem().toString());
            int horatiempoTrayectoria = Integer.parseInt(cbHoraTrayectoria.getSelectedItem().toString());
            int minutoTrayectoria = Integer.parseInt(cbMinutoTrayectoria.getSelectedItem().toString());
            String codigovuelo = txtCodigoVuelo.getText();
            Avion codigoAvion = (Avion) cbAvion.getSelectedItem();
            CapitanVuelo capitan = (CapitanVuelo) cbCapitan.getSelectedItem();
            Date fechaAux = jdcFechaVuelo.getDate();
            LocalDate fecha = fechaAux.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            LocalTime fechaHora = LocalTime.of(horasalida, minutoSalida);
            LocalDateTime fechaSalida = LocalDateTime.of(fecha, fechaHora);
            LocalDateTime fechaLlegada = fechaSalida.plusHours(horatiempoTrayectoria);
            fechaLlegada.plusMinutes(minutoTrayectoria);
            Vuelo vuel = new Vuelo(origen, destino, fechaSalida, fechaLlegada, codigovuelo, codigoAvion, capitan);
            Vuelo vuelo2 = controladorVuelo.validacionOrigen(aeroline, vuel);
            if (!vuelo2.getDestino().equals(vuel.getOrigen())) {
                Vuelo vu1 = new Vuelo(vuelo2.getDestino(), destino, fechaSalida, fechaLlegada, codigovuelo, codigoAvion, capitan);
                JOptionPane.showMessageDialog(null, "No Se puede Modificar el origen");
            } else {
                this.aeroline = controladorVuelo.modificarVuelo(aeroline, vuel);
                actualizarTabla();
                JOptionPane.showMessageDialog(null, "Se Modifico El Vuelo");
                limpiarVuelo();

            }

        } catch (noExisteVueloException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        try {
            String codigovuelo = txtCodigoVuelo.getText();
            this.aeroline = controladorVuelo.eliminarVuelo(aeroline, codigovuelo);
            JOptionPane.showMessageDialog(null, " Se Elimino El Vuelo ");
            actualizarTabla();
            limpiarVuelo();

        } catch (noExisteVueloException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCodigoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoVueloActionPerformed

    private void cbAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAvionActionPerformed

    private void cbCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCapitanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCapitanActionPerformed

    private void btnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudActionPerformed

        try {
             String id = txtCodigoS.getText();
        String observacion = txtObservacion.getText();
        Avion codigoAvion = (Avion) cbAvion.getSelectedItem();
        Date fechaAux = jdcFechaS.getDate();
        LocalDate fecha = fechaAux.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        String estado = "En espera";
        
        SolicitudMantenimiento solicitud = new SolicitudMantenimiento(null, null, id, fecha, estado, observacion, codigoAvion);
       this.aeroline= controladorSolicitudMantenimiento.guardarSolicitud(aeroline, solicitud);
            JOptionPane.showMessageDialog(null, "La Solicitud fue creada");
            limpiarSolicitud();
            actualizarSolicitud();
        } catch (solicitudExistenteexeption e) {
         JOptionPane.showMessageDialog(null, e.getMessage());
           
        }
       

    }//GEN-LAST:event_btnSolicitudActionPerformed

    private void btnBuscarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSActionPerformed
        String id = txtCodigoS.getText();
        SolicitudMantenimiento respuesta = controladorSolicitudMantenimiento.buscarSolicitud(aeroline, id);
        
        if (respuesta != null) {
            txtCodigoS.setText(respuesta.getId());
             jdcFechaS.setDate(java.sql.Date.valueOf(respuesta.getFecha()));
           cbAvion.setSelectedItem(respuesta.getAvion());
        } else {
            JOptionPane.showMessageDialog(null, "No hay Solicitud");
        }
    }//GEN-LAST:event_btnBuscarSActionPerformed

    private void btnModificarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSActionPerformed
        String id = txtCodigoS.getText();
        String observacion = txtObservacion.getText();
        Avion codigoAvion = (Avion) cbAvion.getSelectedItem();
        CapitanVuelo capitan = (CapitanVuelo) cbCapitan.getSelectedItem();
        Date fechaAux = jdcFechaS.getDate();
        LocalDate fecha = fechaAux.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        String estado = "En espera";    
        SolicitudMantenimiento solicitud = new SolicitudMantenimiento(null, null, id, fecha, estado, observacion, codigoAvion);
        boolean respuesta = controladorSolicitudMantenimiento.modificarSolicitud(aeroline, solicitud);
        if (respuesta) {
            limpiarSolicitud();
            actualizarSolicitud();
            JOptionPane.showConfirmDialog(null, "La Solicitud Se Modifico");
        } else {
            JOptionPane.showMessageDialog(null, "Su Solicitud no fue Modificada");
        }
    }//GEN-LAST:event_btnModificarSActionPerformed

    private void btnEliminarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSActionPerformed
        String id = txtCodigoS.getText();
        SolicitudMantenimiento respuesta = controladorSolicitudMantenimiento.buscarSolicitud(aeroline, id);
        boolean respuesta1 = controladorSolicitudMantenimiento.eliminarSolicitud(aeroline, respuesta);
        if (respuesta1) {
            JOptionPane.showMessageDialog(null, "Se Elimino La Solicitud");
            limpiarSolicitud();
            actualizarSolicitud();
        } else {
            JOptionPane.showMessageDialog(null, "No Se Elimino La Solicitud");
        }
    }//GEN-LAST:event_btnEliminarSActionPerformed

    private void txtCodigoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoSActionPerformed

    private void cbAvionSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAvionSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAvionSActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        VentanaChatEmpleado ventana = new VentanaChatEmpleado(aeroline);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChatActionPerformed

    private void actualizarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"ORIGEN", "DESTINO", "FECHA", "HORA SALIDA",
            "TIEMPO TRAYECTORIA", "AVION", "CODIGO VUELO"},
                aeroline.getListaVuelos().size());
        tblTabla.setModel(modelo);
        TableModel modeloDatos = tblTabla.getModel();
        for (int i = 0; i < aeroline.getListaVuelos().size(); i++) {
            Vuelo aux = aeroline.getListaVuelos().get(i);
            SimpleDateFormat standar1 = new SimpleDateFormat("dd/MM/yyyy");
            modeloDatos.setValueAt(aux.getOrigen(), i, 0);
            modeloDatos.setValueAt(aux.getDestino(), i, 1);
            modeloDatos.setValueAt(standar1.format(java.sql.Date.valueOf(aux.getFechaLlegada().toLocalDate())), i, 2);
            modeloDatos.setValueAt(((aux.getFechaSalida().toLocalTime().toString())), i, 3);
            modeloDatos.setValueAt(aux.getFechaLlegada().toLocalTime().toString(), i, 4);
            modeloDatos.setValueAt(aux.getAvion().getModelo(), i, 5);
            modeloDatos.setValueAt(aux.getCodigoVuelo(), i, 6);
        }
    }

    private void actualizarAviones() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"CODIGO", "MODELO", "N° SILLAS"},
                aeroline.getListaAviones().size());
        tblAvion.setModel(modelo);
        TableModel modeloDatos = tblAvion.getModel();
        for (int i = 0; i < aeroline.getListaAviones().size(); i++) {
            Avion aux = aeroline.getListaAviones().get(i);
            modeloDatos.setValueAt(aux.getCodigoAvion(), i, 0);
            modeloDatos.setValueAt(aux.getModelo(), i, 1);
            modeloDatos.setValueAt(aux.getNum_Sillas(), i, 2);
        }
    }

    public void llenarCbCapitan(Aerolinea aero) {
        cbCapitan.removeAllItems();
       
        for (int i = 0; i < aeroline.getListaPersona().size(); i++) {
            if (aeroline.getListaPersona().get(i) instanceof CapitanVuelo) {
                cbCapitan.addItem((CapitanVuelo) (aeroline.getListaPersona().get(i)));
            
            }
        }
    }

    public void llenarCbAvion(Aerolinea aero) {
        cbAvion.removeAllItems();
        cbAvionS.removeAllItems();
        for (int i = 0; i < aeroline.getListaAviones().size(); i++) {
            if (aeroline.getListaAviones().get(i) instanceof Avion) {
                cbAvion.addItem(aeroline.getListaAviones().get(i));
                cbAvionS.addItem(aeroline.getListaAviones().get(i));
            }
        }
    }

    //Método para inicializar el ComboBox de origen
    private void incializarComboBoxOrigen() {
        cbOrigen.removeAllItems();
        cbOrigen.addItem("Armenia");
        cbOrigen.addItem("Bogota");
        cbOrigen.addItem("Manizales");
        cbOrigen.addItem("Pereira");
        cbOrigen.addItem("Cali");
        cbOrigen.addItem("Bucaramanga");
    }

    //Método para inicializar el ComboBox de Destino
    private void incializarComboBoxDestino() {
        cbDestino.removeAllItems();
        cbDestino.addItem("Armenia");
        cbDestino.addItem("Bogota");
        cbDestino.addItem("Manizales");
        cbDestino.addItem("Pereira");
        cbDestino.addItem("Cali");
        cbDestino.addItem("Bucaramanga");
    }

    private void incializarComboBoxHoraSalida() {
        cbHoraSalida.removeAllItems();
        for (int i = 0; i <= 23; i++) {
            String a = String.valueOf(i);
            cbHoraSalida.addItem(a);
        }
    }

    private void incializarComboBoxMinutoSalida() {
        cbMinutoSalida.removeAllItems();
        for (int i = 0; i <= 59; i++) {
            String a = String.valueOf(i);
            cbMinutoSalida.addItem(a);
        }
    }

    private void incializarComboBoxHoraTrayectoria() {
        cbHoraTrayectoria.removeAllItems();
        for (int i = 0; i <= 23; i++) {
            String a = String.valueOf(i);
            cbHoraTrayectoria.addItem(a);
        }
    }

    private void incializarComboBoxMinutoTrayectoria() {
        cbMinutoTrayectoria.removeAllItems();
        for (int i = 0; i <= 59; i++) {
            String a = String.valueOf(i);
            cbMinutoTrayectoria.addItem(a);
        }
    }

    private void limpiarVuelo() {
        cbOrigen.setSelectedIndex(0);
        cbDestino.setSelectedIndex(0);
        cbHoraSalida.setSelectedIndex(0);
        cbMinutoSalida.setSelectedIndex(0);
        cbHoraTrayectoria.setSelectedIndex(0);
        cbMinutoTrayectoria.setSelectedIndex(0);
        txtCodigoVuelo.setText("");
        cbAvion.setSelectedIndex(0);
        cbCapitan.setSelectedIndex(0);
    }

    private void limpiarSolicitud() {
        jdcFechaS.setDate(null);
        txtObservacion.setText("");
        cbMinutoTrayectoria.setSelectedIndex(0);
        txtCodigoS.setText("");
        cbAvionS.setSelectedIndex(0);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarS;
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarS;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarS;
    private javax.swing.JButton btnSolicitud;
    private javax.swing.JComboBox<Avion> cbAvion;
    private javax.swing.JComboBox<Avion> cbAvionS;
    private javax.swing.JComboBox<CapitanVuelo> cbCapitan;
    private javax.swing.JComboBox<String> cbDestino;
    private javax.swing.JComboBox<String> cbHoraSalida;
    private javax.swing.JComboBox<String> cbHoraTrayectoria;
    private javax.swing.JComboBox<String> cbMinutoSalida;
    private javax.swing.JComboBox<String> cbMinutoTrayectoria;
    private javax.swing.JComboBox<String> cbOrigen;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcFechaS;
    private com.toedter.calendar.JDateChooser jdcFechaVuelo;
    private javax.swing.JTable tblAvion;
    private javax.swing.JTable tblSolicitud;
    private javax.swing.JTable tblTabla;
    private javax.swing.JButton txtBuscar;
    private javax.swing.JTextField txtCodigoS;
    private javax.swing.JTextField txtCodigoVuelo;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JButton txtRegistrar;
    // End of variables declaration//GEN-END:variables
}
