package Vista;

import Controlador.ControladorAerolinea;
import Modelo.Aerolinea;
import Modelo.Reserva;
import Modelo.Viajero;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Sebastian Sosa
 */
public class VentanaHistorialViajero extends javax.swing.JFrame {

    Viajero viajero;
    Aerolinea aerolinea;
    ControladorAerolinea controladorAerolinea;

    public VentanaHistorialViajero(Viajero viajero) {
        initComponents();
        setLocationRelativeTo(this);
        this.viajero = viajero;
        this.controladorAerolinea = new ControladorAerolinea();
        actualizartabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablasHistoriaReserva = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblTablasHistoriaReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTablasHistoriaReserva);

        btnAtras.setBackground(new java.awt.Color(255, 214, 94));
        btnAtras.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(299, 299, 299))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAtras)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizartabla() {
        int totalReservas = 0;
        LocalDateTime fechaHoy = LocalDateTime.now();
        for (int i = 0; i < controladorAerolinea.getListaAerolineas().size(); i++) {
            for (int j = 0; j < controladorAerolinea.getListaAerolineas().get(i).getListaVuelos().size(); j++) {
                for (int k = 0; k < controladorAerolinea.getListaAerolineas().get(i).getListaVuelos().get(j).getListaReserva().size(); k++) {
                    totalReservas++;
                }
            }
        }
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"ORIGEN", "DESTINO", "FECHA", "HORA SALIDA",
            "TIEMPO TRAYECTORIA", "AVION", "CODIGO VUELO", "Aereolinea", "Nombre del Viajero"},
                totalReservas);
        tblTablasHistoriaReserva.setModel(modelo);
        TableModel modeloDatos = tblTablasHistoriaReserva.getModel();
        SimpleDateFormat standar1 = new SimpleDateFormat("dd/MM/yyyy");
        int fila = 0;
        for (int i = 0; i < controladorAerolinea.getListaAerolineas().size(); i++) {
            for (int j = 0; j < controladorAerolinea.getListaAerolineas().get(i).getListaVuelos().size(); j++) {
                for (int k = 0; k < controladorAerolinea.getListaAerolineas().get(i).getListaVuelos().get(j).getListaReserva().size(); k++) {
                    if (viajero.getNumDocumento().equals((controladorAerolinea.getListaAerolineas().get(i).getListaVuelos().get(j).
                            getListaReserva().get(k).getViajero().getNumDocumento())) && fechaHoy.isAfter((controladorAerolinea.getListaAerolineas().get(i).getListaVuelos().get(j).
                            getListaReserva().get(k).getVuelo().getFechaSalida()))) {
                        if (fila < totalReservas) {
                            Reserva aux = controladorAerolinea.getListaAerolineas().get(i).getListaVuelos().get(j).getListaReserva().get(k);
                            modeloDatos.setValueAt(aux.getVuelo().getOrigen(), fila, 0);
                            modeloDatos.setValueAt(aux.getVuelo().getDestino(), fila, 1);
                            modeloDatos.setValueAt(standar1.format(java.sql.Date.valueOf(aux.getVuelo().getFechaSalida().toLocalDate())), fila, 2);
                            modeloDatos.setValueAt(((aux.getVuelo().getFechaSalida().toLocalTime().toString())), fila, 3);
                            modeloDatos.setValueAt(aux.getVuelo().getFechaLlegada().toLocalTime().toString(), fila, 4);
                            modeloDatos.setValueAt(aux.getVuelo().getAvion().getModelo(), fila, 5);
                            modeloDatos.setValueAt(aux.getVuelo().getCodigoVuelo(), fila, 6);
                            modeloDatos.setValueAt(controladorAerolinea.getListaAerolineas().get(i).getNombreAerolinea(), fila, 7);
                            modeloDatos.setValueAt(controladorAerolinea.getListaAerolineas().get(i).getListaVuelos().get(j).getListaReserva().get(k).getViajero().getNombre(), fila, 8);
                            fila++;
                        }
                    }
                }
            }
        }
    }
    
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VentanaViajeroMenu ventana = new VentanaViajeroMenu(viajero);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTablasHistoriaReserva;
    // End of variables declaration//GEN-END:variables
}
