package Vista;

import Controlador.ControladorAerolinea;
import Controlador.ControladorSolicitudMantenimiento;
import Exepciones.soliAprovadaException;
import Modelo.SolicitudMantenimiento;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author juan
 */
public class VentanaSolicitudAdmin extends javax.swing.JFrame {

    ControladorAerolinea controladorAerolinea;
    ControladorSolicitudMantenimiento controladorSolicitudMantenimiento;

    public VentanaSolicitudAdmin() {
        initComponents();
        setLocationRelativeTo(this);
        this.controladorAerolinea = new ControladorAerolinea();
        this.controladorSolicitudMantenimiento = new ControladorSolicitudMantenimiento();
        actualizarSolicitud();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReserva = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnChat = new javax.swing.JButton();
        txtTiempo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReserva);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tiempo de responder");

        btnAtras.setBackground(new java.awt.Color(255, 214, 94));
        btnAtras.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(255, 214, 94));
        btnFinalizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnChat.setBackground(new java.awt.Color(255, 214, 94));
        btnChat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnChat.setForeground(new java.awt.Color(0, 0, 0));
        btnChat.setText("Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });

        txtTiempo.setBackground(new java.awt.Color(255, 255, 255));
        txtTiempo.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnChat)
                .addGap(278, 278, 278))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAtras)
                    .addComponent(btnFinalizar)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnChat)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VentanaAdministradorGeneral ventana = new VentanaAdministradorGeneral();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        int filaSeleccionada = tblReserva.getSelectedRow();
        if (filaSeleccionada != -1) {
            String codigo = (String) tblReserva.getValueAt(filaSeleccionada, 0);
            SolicitudMantenimiento soli = controladorSolicitudMantenimiento.verificarSolicitud(codigo);
            VentanaChatAdmin ventana = new VentanaChatAdmin(soli);
            ventana.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila Valida");
        }
    }//GEN-LAST:event_btnChatActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        try {
         if( txtTiempo.getText().isBlank()==false){
            int filaSeleccionada = tblReserva.getSelectedRow();
            String codigo = (String) tblReserva.getValueAt(filaSeleccionada, 0);
            SolicitudMantenimiento soli = controladorSolicitudMantenimiento.verificarSolicitud(codigo);

            if (filaSeleccionada != -1) {
                int tiempo = Integer.parseInt(txtTiempo.getText());
                controladorSolicitudMantenimiento.finalizarSolicitud(soli, tiempo);
                JOptionPane.showMessageDialog(null, "Se aprovo la solicitud");
                actualizarSolicitud();

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una fila Valida");
            }
        }else{
           JOptionPane.showMessageDialog(null, "Llene el espacio de Tiempo a Responder");
         
         }
        } catch (soliAprovadaException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void actualizarSolicitud() {
        int totalSolicitudes = 0;
        for (int i = 0; i < controladorSolicitudMantenimiento.getListaAerolineas().size(); i++) {
            for (int j = 0; j < controladorSolicitudMantenimiento.getListaAerolineas().get(i).getListaSolicitud().size(); j++) {
                totalSolicitudes++;
            }
        }
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"ID", "FECHA", "AVION", "OBSERVACIÓN", "ESTADO"},
                totalSolicitudes);
        tblReserva.setModel(modelo);
        TableModel modeloDatos = tblReserva.getModel();
        int fila = 0;
        for (int i = 0; i < controladorSolicitudMantenimiento.getListaAerolineas().size(); i++) {
            for (int j = 0; j < controladorSolicitudMantenimiento.getListaAerolineas().get(i).getListaSolicitud().size(); j++) {
               if(fila<totalSolicitudes){
                SolicitudMantenimiento aux = controladorSolicitudMantenimiento.getListaAerolineas().get(i).getListaSolicitud().get(j);
                modeloDatos.setValueAt(aux.getId(), fila, 0);
                modeloDatos.setValueAt(aux.getFecha().toString(), fila, 1);
                modeloDatos.setValueAt(aux.getAvion(), fila, 2);
                modeloDatos.setValueAt(aux.getObservacion(), fila, 3);
                modeloDatos.setValueAt(aux.getEstado(), fila, 4);

                fila++;
               }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSolicitudAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSolicitudAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSolicitudAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSolicitudAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSolicitudAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReserva;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
