package Vista;

import Controlador.ControladorAerolinea;
import Controlador.ControladorVuelo;
import Exepciones.avionExistenteException;
import Exepciones.empleadoDuplicadoException;
import Exepciones.empleadoNoexisteException;
import Exepciones.noExisteElAvionException;
import Exepciones.seleccionGeneroInvalidaException;
import Exepciones.usuarioDeAdminYaExistenteException;
import Exepciones.usuarioExistenteException;
import Modelo.Aerolinea;
import Modelo.Avion;
import Modelo.CapitanVuelo;
import Modelo.EmpleadoLogistica;
import Modelo.Persona;
import Modelo.Vuelo;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Sebastian Sosa
 */
public class VentanaAdministradorAerolinea extends javax.swing.JFrame {

    ControladorAerolinea controladorAerolinea;
    Aerolinea aero;

    public VentanaAdministradorAerolinea(Aerolinea aero) {
        initComponents();
        setLocationRelativeTo(this);
        this.controladorAerolinea = new ControladorAerolinea();
        this.aero = aero;
        incializarComboBoxGeneroEm();
        incializarComboBoxGeneroCa();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNumCelular = new javax.swing.JTextField();
        txtNumDocumento = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreEmple = new javax.swing.JTextField();
        txtApellidoEmple = new javax.swing.JTextField();
        txtNumCelularEmple = new javax.swing.JTextField();
        txtNumDocumentoEmple = new javax.swing.JTextField();
        btnRegistrarEmpleado = new javax.swing.JButton();
        cbGeneroEmple = new javax.swing.JComboBox<>();
        btnBuscarEmpleado = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtUsuarioEmple = new javax.swing.JTextField();
        txtContraseniaEmple = new javax.swing.JTextField();
        btnModificarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombreCapitan = new javax.swing.JTextField();
        txtApellidoCapitan = new javax.swing.JTextField();
        txtNumCelularCapitan = new javax.swing.JTextField();
        txtNumDocumentoCapitan = new javax.swing.JTextField();
        btnRegistrarCapitan = new javax.swing.JButton();
        cbGeneroCapitan = new javax.swing.JComboBox<>();
        btnBuscarCapitan = new javax.swing.JButton();
        btnModificarCapitan = new javax.swing.JButton();
        btnEliminarCapitan = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtNumSilla = new javax.swing.JTextField();
        txtCodigoAvion = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtModeloAvion = new javax.swing.JTextField();
        btnRegistrarAvion = new javax.swing.JButton();
        btnBuscarAvion = new javax.swing.JButton();
        btnModificarAvion = new javax.swing.JButton();
        btnEliminarAvion = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Genero");

        jLabel4.setText("Numero Celular");

        jLabel5.setText("Numero Documento");

        btnRegistrar.setText("Registrar");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtNumDocumento)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnRegistrar)
                        .addGap(89, 89, 89)
                        .addComponent(btnLogin)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnLogin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Apellido");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Genero");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Numero Documento");

        txtNombreEmple.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEmple.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreEmple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEmpleKeyTyped(evt);
            }
        });

        txtApellidoEmple.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoEmple.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoEmple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoEmpleKeyTyped(evt);
            }
        });

        txtNumCelularEmple.setBackground(new java.awt.Color(255, 255, 255));
        txtNumCelularEmple.setForeground(new java.awt.Color(0, 0, 0));
        txtNumCelularEmple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCelularEmpleKeyTyped(evt);
            }
        });

        txtNumDocumentoEmple.setBackground(new java.awt.Color(255, 255, 255));
        txtNumDocumentoEmple.setForeground(new java.awt.Color(0, 0, 0));
        txtNumDocumentoEmple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocumentoEmpleKeyTyped(evt);
            }
        });

        btnRegistrarEmpleado.setBackground(new java.awt.Color(255, 214, 94));
        btnRegistrarEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnRegistrarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarEmpleado.setText("Registrar");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });

        cbGeneroEmple.setBackground(new java.awt.Color(255, 255, 255));
        cbGeneroEmple.setForeground(new java.awt.Color(0, 0, 0));
        cbGeneroEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGeneroEmpleActionPerformed(evt);
            }
        });

        btnBuscarEmpleado.setBackground(new java.awt.Color(255, 214, 94));
        btnBuscarEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnBuscarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarEmpleado.setText("Buscar");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Usuario");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Contraseña");

        txtUsuarioEmple.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioEmple.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioEmpleActionPerformed(evt);
            }
        });

        txtContraseniaEmple.setBackground(new java.awt.Color(255, 255, 255));
        txtContraseniaEmple.setForeground(new java.awt.Color(0, 0, 0));

        btnModificarEmpleado.setBackground(new java.awt.Color(255, 214, 94));
        btnModificarEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnModificarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarEmpleado.setText("Modificar");
        btnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEmpleadoActionPerformed(evt);
            }
        });

        btnEliminarEmpleado.setBackground(new java.awt.Color(255, 214, 94));
        btnEliminarEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnEliminarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Numero Celular");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images-min-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(txtNumDocumentoEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbGeneroEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCelularEmple)
                            .addComponent(txtApellidoEmple)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuarioEmple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtContraseniaEmple, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreEmple, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(159, Short.MAX_VALUE)
                        .addComponent(btnRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarEmpleado))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtUsuarioEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtContraseniaEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtApellidoEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbGeneroEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCelularEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDocumentoEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarEmpleado)
                    .addComponent(btnBuscarEmpleado)
                    .addComponent(btnModificarEmpleado)
                    .addComponent(btnEliminarEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Registrar Empleados", jPanel1);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Apellido");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Genero");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Numero Celular");

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Numero Documento");

        txtNombreCapitan.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCapitan.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCapitan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCapitanKeyTyped(evt);
            }
        });

        txtApellidoCapitan.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoCapitan.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCapitanActionPerformed(evt);
            }
        });
        txtApellidoCapitan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoCapitanKeyTyped(evt);
            }
        });

        txtNumCelularCapitan.setBackground(new java.awt.Color(255, 255, 255));
        txtNumCelularCapitan.setForeground(new java.awt.Color(0, 0, 0));
        txtNumCelularCapitan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCelularCapitanKeyTyped(evt);
            }
        });

        txtNumDocumentoCapitan.setBackground(new java.awt.Color(255, 255, 255));
        txtNumDocumentoCapitan.setForeground(new java.awt.Color(0, 0, 0));
        txtNumDocumentoCapitan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocumentoCapitanKeyTyped(evt);
            }
        });

        btnRegistrarCapitan.setBackground(new java.awt.Color(255, 214, 94));
        btnRegistrarCapitan.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnRegistrarCapitan.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarCapitan.setText("Registrar");
        btnRegistrarCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCapitanActionPerformed(evt);
            }
        });

        cbGeneroCapitan.setBackground(new java.awt.Color(255, 255, 255));
        cbGeneroCapitan.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscarCapitan.setBackground(new java.awt.Color(255, 214, 94));
        btnBuscarCapitan.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnBuscarCapitan.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarCapitan.setText("Buscar");
        btnBuscarCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCapitanActionPerformed(evt);
            }
        });

        btnModificarCapitan.setBackground(new java.awt.Color(255, 214, 94));
        btnModificarCapitan.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnModificarCapitan.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarCapitan.setText("Modificar");
        btnModificarCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCapitanActionPerformed(evt);
            }
        });

        btnEliminarCapitan.setBackground(new java.awt.Color(255, 214, 94));
        btnEliminarCapitan.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnEliminarCapitan.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarCapitan.setText("Eliminar");
        btnEliminarCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCapitanActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/62256581-piloto-de-avión-sombrero-uniforme-vector-ilustración-diseño-min-removebg-preview.png"))); // NOI18N
        jLabel17.setText("jLabel17");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumDocumentoCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCelularCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGeneroCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnRegistrarCapitan)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCapitan)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarCapitan)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCapitan)))
                .addGap(157, 157, 157))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombreCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGeneroCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCelularCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDocumentoCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCapitan)
                    .addComponent(btnModificarCapitan)
                    .addComponent(btnBuscarCapitan)
                    .addComponent(btnRegistrarCapitan))
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Registrar Capitanes", jPanel2);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNumSilla.setBackground(new java.awt.Color(255, 255, 255));
        txtNumSilla.setForeground(new java.awt.Color(0, 0, 0));
        txtNumSilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumSillaKeyTyped(evt);
            }
        });

        txtCodigoAvion.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoAvion.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoAvionActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Modelo");

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Codigo");

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Numero de Sillas");

        txtModeloAvion.setBackground(new java.awt.Color(255, 255, 255));
        txtModeloAvion.setForeground(new java.awt.Color(0, 0, 0));
        txtModeloAvion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloAvionKeyTyped(evt);
            }
        });

        btnRegistrarAvion.setBackground(new java.awt.Color(255, 214, 94));
        btnRegistrarAvion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnRegistrarAvion.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarAvion.setText("Registrar");
        btnRegistrarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAvionActionPerformed(evt);
            }
        });

        btnBuscarAvion.setBackground(new java.awt.Color(255, 214, 94));
        btnBuscarAvion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnBuscarAvion.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarAvion.setText("Buscar");
        btnBuscarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAvionActionPerformed(evt);
            }
        });

        btnModificarAvion.setBackground(new java.awt.Color(255, 214, 94));
        btnModificarAvion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnModificarAvion.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarAvion.setText("Modificar");
        btnModificarAvion.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnModificarAvionAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnModificarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAvionActionPerformed(evt);
            }
        });

        btnEliminarAvion.setBackground(new java.awt.Color(255, 214, 94));
        btnEliminarAvion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnEliminarAvion.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarAvion.setText("Eliminar");
        btnEliminarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAvionActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-plane-logo-vector-image_323401-min-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtModeloAvion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txtNumSilla)
                            .addComponent(txtCodigoAvion)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnRegistrarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtCodigoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModeloAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(72, 72, 72)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarAvion)
                    .addComponent(btnModificarAvion)
                    .addComponent(btnBuscarAvion)
                    .addComponent(btnRegistrarAvion))
                .addGap(28, 28, 28)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Registrar Aviones", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Historial", jPanel5);

        jButton1.setBackground(new java.awt.Color(255, 214, 94));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        VentanaLogin ventana = new VentanaLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        String codigo = txtNumDocumentoEmple.getText();
        Persona emple = controladorAerolinea.buscarEmpleado(aero, codigo);
        if (emple != null) {
            txtUsuarioEmple.setText(emple.getUsuario());
            txtContraseniaEmple.setText(emple.getContrasenia());
            txtNombreEmple.setText(emple.getNombre());
            txtApellidoEmple.setText(emple.getApellido());
            cbGeneroEmple.setSelectedItem(emple.getGenero());
            txtNumCelularEmple.setText(emple.getNumCelular());
        } else {
            JOptionPane.showMessageDialog(null, "No Existe El Empleado De Logistica");
        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed

        try {
            String usuario = txtUsuarioEmple.getText();
            String contrasenia = txtContraseniaEmple.getText();
            String nombre = txtNombreEmple.getText();
            String apellido = txtApellidoEmple.getText();
            String Genero = cbGeneroEmple.getSelectedItem().toString();
            String numCelular = txtNumCelularEmple.getText();
            String numDocumento = txtNumDocumentoEmple.getText();
            EmpleadoLogistica emple = new EmpleadoLogistica(nombre, apellido, Genero, numCelular, numDocumento, usuario, contrasenia);
            controladorAerolinea.guardarEmpleado(aero, emple);
            JOptionPane.showMessageDialog(null, "Se Registrado el Empleado De Logistica");
            limpiarEmple();
        } catch (empleadoDuplicadoException | usuarioDeAdminYaExistenteException | usuarioExistenteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }


    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void txtUsuarioEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioEmpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEmpleActionPerformed

    private void txtCodigoAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAvionActionPerformed

    private void btnModificarAvionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnModificarAvionAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarAvionAncestorAdded

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpleadoActionPerformed

        try {
            String usuario = txtUsuarioEmple.getText();
            String contrasenia = txtContraseniaEmple.getText();
            String nombre = txtNombreEmple.getText();
            String apellido = txtApellidoEmple.getText();
            String Genero = cbGeneroEmple.getSelectedItem().toString();
            String numCelular = txtNumCelularEmple.getText();
            String numDocumento = txtNumDocumentoEmple.getText();
            EmpleadoLogistica emple = new EmpleadoLogistica(nombre, apellido, Genero, numCelular, numDocumento, usuario, contrasenia);
            controladorAerolinea.modificarEmpleado(aero, emple);
            JOptionPane.showMessageDialog(null, "Se Modifico el Empleado De Losgistica");
            limpiarEmple();

        } catch (empleadoNoexisteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }


    }//GEN-LAST:event_btnModificarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        try {
            String numDocumento = txtNumDocumentoEmple.getText();
            controladorAerolinea.eliminarEmpleado(aero, numDocumento);
            JOptionPane.showMessageDialog(null, "Se Elimino el Empleado De Logistica");
            limpiarEmple();
        } catch (empleadoNoexisteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }


    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnRegistrarCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCapitanActionPerformed

        try {
            String nombre = txtNombreCapitan.getText();
            String apellido = txtApellidoCapitan.getText();
            String Genero = cbGeneroCapitan.getSelectedItem().toString();
            String numCelular = txtNumCelularCapitan.getText();
            String numDocumento = txtNumDocumentoCapitan.getText();
            CapitanVuelo capi = new CapitanVuelo(nombre, apellido, Genero, numCelular, numDocumento, "-", "-");
            controladorAerolinea.guardarCapitan(aero, capi);
            JOptionPane.showMessageDialog(null, "Se Registrado el Capitan De Vuelo");
            limpiarCapi();
        } catch (empleadoDuplicadoException | seleccionGeneroInvalidaException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

    }//GEN-LAST:event_btnRegistrarCapitanActionPerformed

    private void btnBuscarCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCapitanActionPerformed
        String codigo = txtNumDocumentoCapitan.getText();
        Persona capi = controladorAerolinea.buscarCapitan(aero, codigo);
        if (capi != null) {
            txtNombreCapitan.setText(capi.getNombre());
            txtApellidoCapitan.setText(capi.getApellido());
            cbGeneroCapitan.setSelectedItem(capi.getGenero());
            txtNumCelularCapitan.setText(capi.getNumCelular());
        } else {
            JOptionPane.showMessageDialog(null, "No Existe el Capitan De Vuelo");
        }
    }//GEN-LAST:event_btnBuscarCapitanActionPerformed

    private void btnModificarCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCapitanActionPerformed
        try {
            String nombre = txtNombreCapitan.getText();
            String apellido = txtApellidoCapitan.getText();
            String Genero = cbGeneroCapitan.getSelectedItem().toString();
            String numCelular = txtNumCelularCapitan.getText();
            String numDocumento = txtNumDocumentoCapitan.getText();
            CapitanVuelo capi = new CapitanVuelo(nombre, apellido, Genero, numCelular, numDocumento, "-", "-");
            controladorAerolinea.modificarCapitan(aero, capi);
            JOptionPane.showMessageDialog(null, "Se Modifico el Capitan De Vuelo");
            limpiarCapi();
        } catch (empleadoNoexisteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

    }//GEN-LAST:event_btnModificarCapitanActionPerformed

    private void btnEliminarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAvionActionPerformed
        
        try {
           String codigo = txtCodigoAvion.getText();
        controladorAerolinea.eliminarAvion(aero, codigo);
                JOptionPane.showMessageDialog(null, "Se Elimino el Avión");
            limpiarAvi();
       
        } catch (noExisteElAvionException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
           
        }
     
    }//GEN-LAST:event_btnEliminarAvionActionPerformed

    private void btnModificarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAvionActionPerformed
        try {
            String codigo = txtCodigoAvion.getText();
            String modelo = txtModeloAvion.getText();
            int numSilla = Integer.parseInt(txtNumSilla.getText());
            Avion avi = new Avion(codigo, modelo, numSilla);
            controladorAerolinea.modificarAvion(aero, avi);
            JOptionPane.showMessageDialog(null, "Se Modifico el Avión");
            limpiarAvi();
        } catch (noExisteElAvionException e) {
          JOptionPane.showMessageDialog(null, e.getMessage());
        
        }

      
    }//GEN-LAST:event_btnModificarAvionActionPerformed

    private void btnBuscarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAvionActionPerformed
        String codigo = txtCodigoAvion.getText();
        Avion aux = controladorAerolinea.buscarAvion(aero, codigo);
        if (aux != null) {
            txtCodigoAvion.setText(aux.getCodigoAvion());
            txtModeloAvion.setText(aux.getModelo());
            txtNumSilla.setText(Integer.toString(aux.getNum_Sillas()));
        } else {
            JOptionPane.showMessageDialog(null, "No Existe el Avion");
        }
    }//GEN-LAST:event_btnBuscarAvionActionPerformed

    private void btnRegistrarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAvionActionPerformed

        try {
            String codigo = txtCodigoAvion.getText();
            String modelo = txtModeloAvion.getText();
            int numSilla = Integer.parseInt(txtNumSilla.getText());
            Avion avi = new Avion(codigo, modelo, numSilla);
            controladorAerolinea.guardarAvion(aero, avi);
            JOptionPane.showMessageDialog(null, "Se Registrado el Avión");
            limpiarAvi();

        } catch (avionExistenteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnRegistrarAvionActionPerformed

    private void btnEliminarCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCapitanActionPerformed
        try {
            String nombre = txtNombreCapitan.getText();
            String apellido = txtApellidoCapitan.getText();
            String Genero = cbGeneroCapitan.getSelectedItem().toString();
            String numCelular = txtNumCelularCapitan.getText();
            String numDocumento = txtNumDocumentoCapitan.getText();
            CapitanVuelo capi = new CapitanVuelo(nombre, apellido, Genero, numCelular, numDocumento, "-", "-");
            controladorAerolinea.eliminarCapitan(aero, capi);
            JOptionPane.showMessageDialog(null, "Se Elimino el Capitan De Vuelo");
            limpiarCapi();
        } catch (empleadoNoexisteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btnEliminarCapitanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaLogin ventana = new VentanaLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbGeneroEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeneroEmpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGeneroEmpleActionPerformed

    private void txtNombreEmpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEmpleKeyTyped
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' || letras > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtNombreEmpleKeyTyped

    private void txtApellidoEmpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoEmpleKeyTyped
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' || letras > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtApellidoEmpleKeyTyped

    private void txtNumCelularEmpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCelularEmpleKeyTyped
        char num = evt.getKeyChar();
        if (num < '0' || num > '9')
            evt.consume();
    }//GEN-LAST:event_txtNumCelularEmpleKeyTyped

    private void txtNumDocumentoEmpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocumentoEmpleKeyTyped
        char num = evt.getKeyChar();
        if (num < '0' || num > '9')
            evt.consume();
    }//GEN-LAST:event_txtNumDocumentoEmpleKeyTyped

    private void txtNombreCapitanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCapitanKeyTyped
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' || letras > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtNombreCapitanKeyTyped

    private void txtApellidoCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCapitanActionPerformed

    }//GEN-LAST:event_txtApellidoCapitanActionPerformed

    private void txtNumCelularCapitanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCelularCapitanKeyTyped
        char num = evt.getKeyChar();
        if (num < '0' || num > '9')
            evt.consume();
    }//GEN-LAST:event_txtNumCelularCapitanKeyTyped

    private void txtApellidoCapitanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoCapitanKeyTyped
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' || letras > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtApellidoCapitanKeyTyped

    private void txtNumDocumentoCapitanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocumentoCapitanKeyTyped
        char num = evt.getKeyChar();
        if (num < '0' || num > '9')
            evt.consume();
    }//GEN-LAST:event_txtNumDocumentoCapitanKeyTyped

    private void txtModeloAvionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloAvionKeyTyped
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' || letras > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtModeloAvionKeyTyped

    private void txtNumSillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSillaKeyTyped
        char num = evt.getKeyChar();
        if (num < '0' || num > '9')
            evt.consume();
    }//GEN-LAST:event_txtNumSillaKeyTyped

    private void actualizarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"ORIGEN", "DESTINO", "FECHA", "HORA SALIDA",
            "TIEMPO TRAYECTORIA", "AVION", "CODIGO VUELO"},
                aero.getListaVuelos().size());
        tblTabla.setModel(modelo);
        TableModel modeloDatos = tblTabla.getModel();
        for (int i = 0; i < aero.getListaVuelos().size(); i++) {
            Vuelo aux = aero.getListaVuelos().get(i);
            SimpleDateFormat standar1 = new SimpleDateFormat("dd/MM/yyyy");
            modeloDatos.setValueAt(aux.getOrigen(), i, 0);
            modeloDatos.setValueAt(aux.getDestino(), i, 1);
            modeloDatos.setValueAt(standar1.format(java.sql.Date.valueOf(aux.getFechaLlegada().toLocalDate())), i, 2);
            modeloDatos.setValueAt(((aux.getFechaSalida().toLocalTime().toString())), i, 3);
            modeloDatos.setValueAt(aux.getFechaLlegada().toLocalTime().toString(), i, 4);
            modeloDatos.setValueAt(aux.getAvion().getModelo(), i, 5);
            modeloDatos.setValueAt(aux.getCodigoVuelo(), i, 6);
        }
    }

    private void limpiarEmple() {
        txtUsuarioEmple.setText("");
        txtContraseniaEmple.setText("");
        txtNombreEmple.setText("");
        txtApellidoEmple.setText("");
        cbGeneroEmple.setSelectedIndex(0);
        txtNumCelularEmple.setText("");
        txtNumDocumentoEmple.setText("");
    }

    private void limpiarCapi() {
        txtNombreCapitan.setText("");
        txtApellidoCapitan.setText("");
        cbGeneroCapitan.setSelectedIndex(0);
        txtNumCelularCapitan.setText("");
        txtNumDocumentoCapitan.setText("");
    }

    private void limpiarAvi() {
        txtCodigoAvion.setText("");
        txtModeloAvion.setText("");
        txtNumSilla.setText("");
    }

    //Método para inicializar el ComboBox de Genero
    private void incializarComboBoxGeneroEm() {
        cbGeneroEmple.removeAllItems();
        cbGeneroEmple.addItem("Seleccionar");
        cbGeneroEmple.addItem("Hombre");
        cbGeneroEmple.addItem("Mujer");
    }

    //Método para inicializar el ComboBox de Genero
    private void incializarComboBoxGeneroCa() {
        cbGeneroCapitan.removeAllItems();
        cbGeneroCapitan.addItem("Seleccionar");
        cbGeneroCapitan.addItem("Hombre");
        cbGeneroCapitan.addItem("Mujer");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAvion;
    private javax.swing.JButton btnBuscarCapitan;
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnEliminarAvion;
    private javax.swing.JButton btnEliminarCapitan;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnModificarAvion;
    private javax.swing.JButton btnModificarCapitan;
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarAvion;
    private javax.swing.JButton btnRegistrarCapitan;
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JComboBox<String> cbGeneroCapitan;
    private javax.swing.JComboBox<String> cbGeneroEmple;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoCapitan;
    private javax.swing.JTextField txtApellidoEmple;
    private javax.swing.JTextField txtCodigoAvion;
    private javax.swing.JTextField txtContraseniaEmple;
    private javax.swing.JTextField txtModeloAvion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCapitan;
    private javax.swing.JTextField txtNombreEmple;
    private javax.swing.JTextField txtNumCelular;
    private javax.swing.JTextField txtNumCelularCapitan;
    private javax.swing.JTextField txtNumCelularEmple;
    private javax.swing.JTextField txtNumDocumento;
    private javax.swing.JTextField txtNumDocumentoCapitan;
    private javax.swing.JTextField txtNumDocumentoEmple;
    private javax.swing.JTextField txtNumSilla;
    private javax.swing.JTextField txtUsuarioEmple;
    // End of variables declaration//GEN-END:variables
}
