package Vista;

/**
 *
 * @author Sebastian Sosa
 */
public class VentanaAdministradorGeneral extends javax.swing.JFrame {

    
    public VentanaAdministradorGeneral() {
        initComponents();
        setLocationRelativeTo(this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jLogin = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuAdminAereo = new javax.swing.JMenu();
        MenuMantenimiento = new javax.swing.JMenu();
        menuGestionControl = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OIG-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLogin.setForeground(new java.awt.Color(153, 255, 255));
        jLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mbrilogout_99583.png"))); // NOI18N
        jLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginMouseClicked(evt);
            }
        });
        jMenuBar1.add(jLogin);

        jMenu3.setText("Registrar");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        MenuAdminAereo.setText("Gestion  de Administradores");
        MenuAdminAereo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAdminAereoMouseClicked(evt);
            }
        });
        jMenu3.add(MenuAdminAereo);

        MenuMantenimiento.setText("Gestores Mantenimiento");
        MenuMantenimiento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MenuMantenimientoStateChanged(evt);
            }
        });
        MenuMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMantenimientoMouseClicked(evt);
            }
        });
        MenuMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMantenimientoActionPerformed(evt);
            }
        });
        jMenu3.add(MenuMantenimiento);

        jMenuBar1.add(jMenu3);

        menuGestionControl.setText("Solicitud de Mantenimiento");
        menuGestionControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGestionControlMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuGestionControl);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAdminAereoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdminAereoMouseClicked
        RegistrarAdminAerolinea adminA = new RegistrarAdminAerolinea();
        adminA.setVisible(true);
        adminA.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_MenuAdminAereoMouseClicked

    private void MenuMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMantenimientoMouseClicked
        RegistrarGestor gestor = new RegistrarGestor();
        gestor.setVisible(true);
        gestor.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_MenuMantenimientoMouseClicked

    private void menuGestionControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGestionControlMouseClicked
        VentanaSolicitudAdmin soli = new VentanaSolicitudAdmin();
        soli.setVisible(true);
        soli.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_menuGestionControlMouseClicked

    private void jLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginMouseClicked
        VentanaLogin login = new VentanaLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(this);
        this.dispose();

    }//GEN-LAST:event_jLoginMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void MenuMantenimientoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MenuMantenimientoStateChanged

    }//GEN-LAST:event_MenuMantenimientoStateChanged

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void MenuMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMantenimientoActionPerformed

    }//GEN-LAST:event_MenuMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdminAereo;
    private javax.swing.JMenu MenuMantenimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jLogin;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuGestionControl;
    // End of variables declaration//GEN-END:variables
}
